In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pwd

'/projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene'

In [3]:
import sys, os
import pandas as pd

def add_path(p: str):
    if p not in sys.path:
        sys.path.append(p)

add_path(os.environ['LP_ROOT'])
import project

add_path(os.environ['PROJECT'] + '/' + 'param_search')
import param_search as ps

ps.set_backend('sge')
ps.set_verbose(False)

# Gather examples

In [4]:
from pathlib import Path
#data_root = Path(os.environ['LP_ROOT'] / 'data' / 'COPDGene'
data_root = Path(os.environ['PRIVATE']) / 'data' / 'COPDGene'
for p in data_root.iterdir():
    print(p)

/restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-22.txt
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-22.csv
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/subject_files.txt
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/Images
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/sample1000_2025-07-17.csv
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/DISK_USAGE
/restricted/projectnb/batmanlab/mragoza/data/COPDGene/ClinicalData

In [5]:
subject_file = data_root / 'sample1000_2025-07-22.csv'
subject_list = list(pd.read_csv(subject_file, sep='\t').sid)
subject_list

['16514P',
 '20748Q',
 '11007Z',
 '14771Z',
 '13651K',
 '15900P',
 '15312Y',
 '21042H',
 '21877G',
 '10127E',
 '23577E',
 '13816Q',
 '21559S',
 '25335Q',
 '23023N',
 '10572Z',
 '10887Y',
 '21410K',
 '17920F',
 '14684E',
 '16132B',
 '17862R',
 '11746L',
 '25728J',
 '20609C',
 '16637F',
 '13297S',
 '25767T',
 '25695U',
 '21572K',
 '15078Q',
 '15297C',
 '14857J',
 '13460D',
 '18840M',
 '12506W',
 '11498S',
 '21611U',
 '15088T',
 '12831H',
 '19612E',
 '19784H',
 '10217F',
 '23037Y',
 '25130Y',
 '15623P',
 '19027T',
 '14380K',
 '10212V',
 '16060C',
 '19356M',
 '22357L',
 '25923H',
 '21189L',
 '24608U',
 '15204V',
 '11743F',
 '11879E',
 '12477P',
 '10815Z',
 '17790S',
 '15489L',
 '11850G',
 '13034M',
 '17255W',
 '14632L',
 '26066U',
 '18184E',
 '15532M',
 '19558Y',
 '20640W',
 '21741H',
 '18015H',
 '17137Q',
 '12422Q',
 '15699W',
 '21933Q',
 '18397V',
 '14550J',
 '20703U',
 '21004Z',
 '24581A',
 '24331D',
 '17505T',
 '15894U',
 '16977D',
 '18935X',
 '19410S',
 '18515B',
 '21399W',
 '21899Q',
 '16091N',
 '17617E',
 '23574Y',
 '11943N',
 '12962W',
 '17104B',
 '20064M',
 '16605S',
 '13170U',
 '24954N',
 '20400C',
 '24682G',
 '24012N',
 '25888F',
 '21052K',
 '20696X',
 '17385J',
 '21223L',
 '13916U',
 '14633N',
 '16021S',
 '18801C',
 '20981W',
 '19819A',
 '21521T',
 '11193W',
 '17939A',
 '18153T',
 '24271L',
 '14217Z',
 '15424J',
 '24514L',
 '21892C',
 '23239K',
 '21083V',
 '17233M',
 '10539B',
 '19091C',
 '10560S',
 '25410E',
 '18798N',
 '25601L',
 '18434B',
 '19627R',
 '16347W',
 '12676V',
 '16853L',
 '24973R',
 '13084B',
 '15163H',
 '24711N',
 '11235M',
 '21587X',
 '13071S',
 '25096Y',
 '23725T',
 '19324Z',
 '21813G',
 '26112B',
 '11350M',
 '14084G',
 '22873D',
 '15827F',
 '19880D',
 '13845X',
 '13264D',
 '18629Q',
 '20024A',
 '12651F',
 '18687E',
 '21168D',
 '11198G',
 '11783R',
 '25674M',
 '10332F',
 '20385G',
 '20088A',
 '20623W',
 '25407P',
 '23930U',
 '15473W',
 '19922T',
 '20453X',
 '19478A',
 '24394B',
 '18761Q',
 '15650S',
 '14417H',
 '16823C',
 '21679C',
 '20678V',
 '17144N',
 '19849J',
 '20375D',
 '20770J',
 '14788Q',
 '17922J',
 '15549D',
 '15073G',
 '26004Y',
 '18830J',
 '25914G',
 '18317X',
 '24867S',
 '13350W',
 '19839G',
 '14332Z',
 '14157H',
 '17847V',
 '21176C',
 '25703T',
 '22855B',
 '11713W',
 '21175A',
 '14329K',
 '15350G',
 '13901H',
 '24744C',
 '25007Z',
 '17428B',
 '21469R',
 '25347X',
 '22224S',
 '15807Z',
 '14924Y',
 '25900V',
 '20005W',
 '25310A',
 '25125F',
 '14668G',
 '25311C',
 '14705M',
 '13282F',
 '10181K',
 '24873N',
 '18593V',
 '19549X',
 '21224N',
 '13998W',
 '12519F',
 '19396Y',
 '20149U',
 '16064K',
 '25894A',
 '22151R',
 '22135T',
 '13488Z',
 '23636U',
 '19637U',
 '20306K',
 '20412J',
 '16700M',
 '11947V',
 '19049D',
 '12825M',
 '19393S',
 '18374J',
 '10301U',
 '15072E',
 '24638D',
 '18714H',
 '14013J',
 '25950K',
 '19139E',
 '15911U',
 '13103F',
 '25072K',
 '13528L',
 '21106H',
 '15635W',
 '26071N',
 '23705N',
 '21769D',
 '15502D',
 '18126Q',
 '18940Q',
 '10736D',
 '20867Y',
 '15413E',
 '19024N',
 '17089F',
 '20668S',
 '19096M',
 '13728T',
 '10566E',
 '12418Z',
 '13255C',
 '22002A',
 '23136A',
 '23052U',
 '14704K',
 '17433U',
 '21163T',
 '16540Q',
 '21065T',
 '10947Q',
 '25552Y',
 '13370C',
 '19733Q',
 '16058P',
 '11721V',
 '19950Y',
 '23743V',
 '12812D',
 '10512H',
 '14646W',
 '13111E',
 '14113N',
 '12607C',
 '15272M',
 '17247X',
 '13358M',
 '22678F',
 '14845C',
 '10179X',
 '10524O',
 '22986Q',
 '22487Y',
 '13507D',
 '10367Y',
 '17011U',
 '22504Y',
 '19367R',
 '10432J',
 '14309E',
 '13719S',
 '10481W',
 '23940X',
 '20188E',
 '21837U',
 '10049K',
 '14729A',
 '10523M',
 '21484N',
 '23526N',
 '11972U',
 '20970R',
 '16402E',
 '13498C',
 '17557M',
 '16613R',
 '13340T',
 '13682V',
 '24576H',
 '15537W',
 '23091E',
 '18043M',
 '21615C',
 '11903B',
 '15898C',
 '10155J',
 '12139V',
 '20006Y',
 '19730K',
 '18682U',
 '26012X',
 '21886H',
 '11998M',
 '16537B',
 '22389Y',
 '20589W',
 '16675N',
 '19339M',
 '22308Y',
 '22827W',
 '10817D',
 '20195B',
 '10314D',
 '12052J',
 '14180C',
 '14905U',
 '21272Y',
 '18808Q',
 '12593R',
 '21604X',
 '11120V',
 '25120V',
 '13945B',
 '24113T',
 '18140K',
 '14293P',
 '22031H',
 '23741R',
 '22983K',
 '13301J',
 '14834X',
 '15319M',
 '16065M',
 '10663C',
 '11477K',
 '10709A',
 '24714T',
 '25694S',
 '14462M',
 '23558A',
 '22617L',
 '22182C',
 '13489B',
 '12478R',
 '15909H',
 '21765V',
 '16527Y',
 '23549Z',
 '11281T',
 '17836Q',
 '10502E',
 '13407Z',
 '15488J',
 '19560L',
 '11195A',
 '19415C',
 '23657C',
 '20659R',
 '18351X',
 '10646C',
 '24279B',
 '23155E',
 '16069U',
 '13273E',
 '10265Q',
 '19887R',
 '15040R',
 '21622Z',
 '16300W',
 '17995K',
 '11224H',
 '22092B',
 '10395D',
 '10124Y',
 '18677B',
 '16716B',
 '23284P',
 '11440N',
 '11085T',
 '11292Y',
 '20117H',
 '11255S',
 '14875L',
 '11613S',
 '16076R',
 '11226L',
 '11830A',
 '13242T',
 '12248A',
 '13248F',
 '14525K',
 '11716C',
 '22483Q',
 '15082H',
 '16472Z',
 '11752G',
 '22600U',
 '17722B',
 '25276A',
 '23686J',
 '22726Q',
 '22261Y',
 '20543Y',
 '11901X',
 '10233D',
 '10888A',
 '18563M',
 '22928C',
 '12223K',
 '11329V',
 '10908G',
 '13384N',
 '17102X',
 '14508K',
 '23011G',
 '25320D',
 '19594C',
 '10728E',
 '24646C',
 '25602N',
 '15152C',
 '22464M',
 '19679K',
 '24106W',
 '14075F',
 '10880K',
 '21614A',
 '10724W',
 '17629L',
 '25926N',
 '25403H',
 '21968J',
 '18982G',
 '24269Y',
 '24154H',
 '20977F',
 '14526M',
 '13799Q',
 '22667A',
 '22170V',
 '10705S',
 '24810P',
 '21438G',
 '10634V',
 '16216H',
 '15384X',
 '13925V',
 '17337Y',
 '12851N',
 '14261C',
 '21660H',
 '15232A',
 '25389N',
 '18525E',
 '19785J',
 '15165L',
 '14774F',
 '11750C',
 '20803Y',
 '23193M',
 '23656A',
 '18703C',
 '15934G',
 '19598K',
 '16440M',
 '16045G',
 '19783F',
 '10130T',
 '10261I',
 '18519J',
 '18452D',
 '21850M',
 '17955Y',
 '17473G',
 '15237K',
 '24449A',
 '11211Y',
 '24123W',
 '17173U',
 '24705S',
 '18274F',
 '11858W',
 '20566K',
 '20008C',
 '13341V',
 '18674V',
 '17897K',
 '10196X',
 '10973R',
 '15929N',
 '16747M',
 '15217E',
 '20296H',
 '11506R',
 '24447W',
 '16573F',
 '19666B',
 '17366F',
 '24383W',
 '24761C',
 '20976D',
 '22637R',
 '10842C',
 '14278T',
 '16277B',
 '11063J',
 '14683C',
 '24757L',
 '20901Y',
 '21419C',
 '22536L',
 '13533E',
 '23077K',
 '12861Q',
 '22113J',
 '11114A',
 '23746B',
 '19921R',
 '12903G',
 '15221V',
 '10056H',
 '22592V',
 '21170Q',
 '10564A',
 '23934C',
 '12683S',
 '14330V',
 '21384J',
 '11404J',
 '17573K',
 '24059N',
 '24950F',
 '14732P',
 '11005V',
 '10490X',
 '16294B',
 '22912N',
 '21153Q',
 '14201K',
 '20378J',
 '13053Q',
 '11468J',
 '19143V',
 '24887Y',
 '15905Z',
 '11616Y',
 '21538K',
 '21800X',
 '15450K',
 '23181F',
 '24064G',
 '21586V',
 '11676Q',
 '10153F',
 '24691H',
 '10227I',
 '19251Y',
 '11516U',
 '22116P',
 '23124T',
 '12339D',
 '21010U',
 '10919L',
 '14987W',
 '10213X',
 '25309P',
 '12878H',
 '21526D',
 '14121M',
 '11782P',
 '12362Y',
 '22597F',
 '15262J',
 '20592L',
 '12187G',
 '19056A',
 '13419G',
 '20286E',
 '14173F',
 '10829K',
 '11618C',
 '23094K',
 '17212E',
 '22253Z',
 '17904H',
 '12905K',
 '18278N',
 '24181K',
 '21293G',
 '23618S',
 '21778E',
 '11514Q',
 '10571X',
 '11545B',
 '21064R',
 '13736S',
 '13092A',
 '12231J',
 '22663S',
 '16266W',
 '20019H',
 '13428H',
 '13501R',
 '11363V',
 '23821P',
 '25303D',
 '19912Q',
 '12147U',
 '12146S',
 '17266B',
 '17894E',
 '18403Q',
 '24679R',
 '15799A',
 '11260L',
 '22114L',
 '10561U',
 '10990R',
 '12466K',
 '14031L',
 '25782P',
 '22759F',
 '21640B',
 '10568I',
 '23074E',
 '18103E',
 '11819M',
 '18341U',
 '18451B',
 '11512M',
 '10328O',
 '14863E',
 '18364G',
 '13149D',
 '15357U',
 '22566U',
 '11852K',
 '14047A',
 '21647P',
 '21508B',
 '13648V',
 '25380V',
 '11353S',
 '13578A',
 '23816W',
 '14837D',
 '22198R',
 '15840X',
 '14745Y',
 '20807G',
 '10761C',
 '11556G',
 '20622U',
 '11240F',
 '24137H',
 '25328T',
 '12608E',
 '11027F',
 '17509B',
 '23902P',
 '15661X',
 '22210H',
 '22193H',
 '25360P',
 '21595W',
 '15164J',
 '10843E',
 '25051C',
 '15527T',
 '22497B',
 '16142E',
 '21391G',
 '25991Y',
 '20632X',
 '17461Z',
 '10883Q',
 '14685G',
 '22604C',
 '21279M',
 '10567G',
 '10478H',
 '25231E',
 '24390T',
 '10641S',
 '19760T',
 '22495X',
 '13267J',
 '13354E',
 '15965R',
 '20151H',
 '10635X',
 '18845W',
 '24927K',
 '21012Y',
 '24205Y',
 '14240U',
 '22055V',
 '13093C',
 '23165H',
 '13365J',
 '24151B',
 '15156K',
 '15607R',
 '22946E',
 '16059R',
 '10081G',
 '20529E',
 '19913S',
 '23269T',
 '25835K',
 '22745U',
 '23266N',
 '18736R',
 '24830V',
 '22484S',
 '19579G',
 '14991N',
 '11325N',
 '21398U',
 '25205D',
 '18553J',
 '14374P',
 '12336X',
 '20435V',
 '23150U',
 '15848N',
 '23310Q',
 '23699S',
 '15606P',
 '14307A',
 '25245P',
 '11123B',
 '19686H',
 '11708D',
 '23252C',
 '14471N',
 '15885T',
 '23326F',
 '25003R',
 '10017X',
 '10426O',
 '22891F',
 '15745D',
 '20332L',
 '23803N',
 '24684K',
 '13530Y',
 '14386W',
 '24643W',
 '24350H',
 '18786G',
 '10458B',
 '14880E',
 '18505Y',
 '13864B',
 '11455A',
 '12795D',
 '25165R',
 '24562W',
 '14232V',
 '10975V',
 '15811Q',
 '23075G',
 '21556M',
 '23293Q',
 '22423Y',
 '19908Z',
 '21838W',
 '12630X',
 '22148C',
 '24186U',
 '25400B',
 '10624S',
 '25704V',
 '21844R',
 '15349V',
 '23819C',
 '12516Z',
 '25454Y',
 '12964A',
 '11881R',
 '26146S',
 '21433W',
 '12515X',
 '21494Q',
 '22746W',
 '11247T',
 '23851Y',
 '12816L',
 '13383L',
 '10552T',
 '13573Q',
 '15212U',
 '15267T',
 '19429N',
 '16954R',
 '13686D',
 '22736T',
 '16783Q',
 '15102N',
 '23799W',
 '13704F',
 '23342D',
 '20689A',
 '23500V',
 '18395R',
 '11866V',
 '10020M',
 '24763G',
 '11225J',
 '18871X',
 '17757U',
 '16390X',
 '24989G',
 '10699X',
 '15271K',
 '14964K',
 '23436M',
 '18498B',
 '21150K',
 '10961K',
 '11139Q',
 '25388L',
 '12560C',
 '24318L',
 '18886K',
 '14814R',
 '24634V',
 '23838G',
 '14257L',
 '22920M',
 '17533Y',
 '13477U',
 '13632G',
 '24377B',
 '17688B',
 '22348K',
 '22832P',
 '12069A',
 '12457J',
 '14390N',
 '10794R',
 '20682M',
 '11560X',
 '17022Z',
 '12895H',
 '19059G',
 '16128K',
 '11690K',
 '14194N',
 '24116Z',
 '24396F',
 '22078H',
 '11153K',
 '16463Y',
 '10849Q',
 '13767D',
 '19673Y',
 '16353R',
 '14133T',
 '22877L',
 '13563N',
 '14817X',
 '13398Y',
 '21897M',
 '11049P',
 '16411F',
 '17409X',
 '13702B',
 '15075K',
 '23312U',
 '23287V',
 '11221B',
 '10114V',
 '10245K',
 '11542V',
 '13586Z',
 '11600J',
 '15132W',
 '14909C',
 '21534C',
 '11815E',
 '16118H',
 '22430V',
 '24911V',
 '10503G',
 '22312P',
 '21842N',
 '24777R',
 '23615M',
 '15690E',
 '22961A',
 '14241W',
 '24080E',
 '20349C',
 '15617U',
 '11968D',
 '10372R',
 '10031R',
 '22325Y',
 '10211T',
 '10469G',
 '24438V',
 '12599D',
 '10806Y',
 '13780V',
 '25943N',
 '13947F',
 '20102U',
 '17476M',
 '12696B',
 '21467N',
 '18960W',
 '17414Q',
 '20738N',
 '17041D',
 '20818L',
 '13866F',
 '20792T',
 '23108V',
 '21461B',
 '10679R',
 '10096T',
 '15140V',
 '11181P',
 '12273Z',
 '13542F',
 '25381X',
 '24213X',
 '11828N',
 '24431H',
 '24480U',
 '13404T',
 '18633H',
 '17952S',
 '13517G',
 '20245Q',
 '22720E',
 '24348U',
 '22914R',
 '24652X',
 '13065X',
 '25762J',
 '24699X',
 '10507O',
 '11267Z',
 '17696A',
 '15224B',
 '14754Z',
 '20519B',
 '12294H',
 '23123R',
 '16546C',
 '11099E']

In [17]:
base_dir = '2026-08-08_preprocess'

template = '''\
#!/bin/bash -l
#$ -N {job_name}
#$ -P batmanlab
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_memory=16G
#$ -l h_rt=12:00:00
set -eo pipefail

mamba activate $PROJECT/mambaforge/envs/warp

export PYTHONPATH=$LP_ROOT:$PROJECT:$PYTHOPATH

python $LP_ROOT/scripts/preprocess.py {config} \\
    --set dataset.name={data_name} \\
    --set dataset.root={data_root} \\
    --set dataset.examples.subjects=[{subject}] \\
    --set dataset.examples.variant={variant} \\
    --set dataset.examples.pipeline_tags.material_properties={mat_tag} \\
    --set dataset.examples.pipeline_tags.forward_simulation={fwd_tag} \\
    --set preprocessing.forward_simulation.pde_solver.material_type={mat_type}

'''
name_format = 'job_{params_hash}'

grid = ps.param_grid(
    config='2026-08-08_config.yaml',
    data_name='COPDGene',
    data_root=str(data_root),
    subject=subject_list,
    mat_tag='bela',
    fwd_tag='linear',
    mat_type='linear',
    variant='2026-08-08'
)

ps.param_grid(  # TODO
    config='2026-08-08_config.yaml',
    data_name='COPDGene',
    data_root=str(data_root),
    subject=subject_list,
    mat_tag='bela',
    fwd_tag='stvk',
    mat_type='stvk',
    variant='2026-08-08'
)
len(grid)

1000

In [18]:
%autoreload
try:
    jobs = ps.setup(base_dir, template, name_format, grid, overwrite=True)
except OSError:
    jobs = ps.load(base_dir)

jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params_json,params_hash,params.config,params.data_name,params.data_root,params.subject,params.mat_tag,params.fwd_tag,params.mat_type,params.variant
0,job_ead9ab1e5bc03c66,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",ead9ab1e5bc03c66,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,16514P,bela,linear,linear,2026-08-08
1,job_96ef0272ef81ee7e,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",96ef0272ef81ee7e,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,20748Q,bela,linear,linear,2026-08-08
2,job_4d5d759871906077,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",4d5d759871906077,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,11007Z,bela,linear,linear,2026-08-08
3,job_62c1bdeb21500ce0,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",62c1bdeb21500ce0,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,14771Z,bela,linear,linear,2026-08-08
4,job_1a856f1cecae8f51,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",1a856f1cecae8f51,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,13651K,bela,linear,linear,2026-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_22f2adacb02a421c,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",22f2adacb02a421c,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,20519B,bela,linear,linear,2026-08-08
996,job_b1e67f498dc392b6,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",b1e67f498dc392b6,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,12294H,bela,linear,linear,2026-08-08
997,job_2f617f39d23060c8,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",2f617f39d23060c8,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,23123R,bela,linear,linear,2026-08-08
998,job_bef061b64dfcfc4e,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",bef061b64dfcfc4e,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,16546C,bela,linear,linear,2026-08-08
999,job_2ee27f6ba5ec4ec2,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",2ee27f6ba5ec4ec2,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,11099E,bela,linear,linear,2026-08-08

In [19]:
jobs = ps.submit(jobs)

In [8]:
%autoreload
jobs = ps.recover(jobs)
jobs = ps.status(jobs)
jobs = ps.history(jobs)
jobs = ps.collect(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.mat_type,params.variant,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
0,jobead9ab1e5bc03c66,SUBMITTED,1,7159234,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
1,job96ef0272ef81ee7e,SUBMITTED,1,7159235,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
2,job4d5d759871906077,SUBMITTED,1,7159236,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
3,job62c1bdeb21500ce0,SUBMITTED,1,7159237,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
4,job1a856f1cecae8f51,SUBMITTED,1,7159238,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job22f2adacb02a421c,SUBMITTED,1,7160229,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
996,jobb1e67f498dc392b6,SUBMITTED,1,7160230,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
997,job2f617f39d23060c8,SUBMITTED,1,7160231,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
998,jobbef061b64dfcfc4e,SUBMITTED,1,7160232,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>
999,job2ee27f6ba5ec4ec2,SUBMITTED,1,7160233,None,None,,usage: preprocess.py [-h] [--set KEY=VAL] conf...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,2026-08-08,NaN,NaN,NaN,NaN,NaN,False,<NA>,<NA>

In [9]:
jobs.groupby('job_state').count()

,job_name,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,script_path,...,params.mat_type,params.variant,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
job_state,,,,,,,,,,,,,,,,,,,,,
SUBMITTED,1000,1000,1000,0,0,1000,1000,1000,1000,1000,...,1000,1000,0,0,0,0,0,1000,0,0

In [10]:
# classify error messages
for j, row in jobs.iterrows():
    if pd.isnull(row.stderr):
        print(f'{j}: No stderr file')
    elif not str(row.stderr).strip():
        print(f'{j}: No error message')
    elif 'Non-positive density' in row.stderr:
        print(f'{j}: Non-positive density')
    elif 'CUDA out of memory' in row.stderr or ('Failed to allocate' in row.stderr and 'bytes on device \'cuda' in row.stderr):
        print(f'{j}: GPU out of memory')
    elif 'Exuding' in row.stderr or ('Moving #' in row.stderr and 'addr:' in row.stderr):
        print(f'{j}: pygalmesh output')
    elif 'construct initial points' in row.stderr:
        print(f'{j}: pygalmesh error?')
    else:
        print(f'{j}: Uncategorized')
        raise RuntimeError(f'Uncategorized stderr for job index {j}:\n{row.stderr}')

0: Uncategorized

RuntimeError: Uncategorized stderr for job index 0:
usage: preprocess.py [-h] [--set KEY=VAL] config
preprocess.py: error: unrecognized arguments:

In [18]:
print(jobs.iloc[261].stdout)

Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf_domain.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/lung_airways.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/consolidation.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/lung_arteries.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/lt-950.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/lung_veins.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/lt-850.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/ggo.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/nodule.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf/lt-910.nii.gz
Saving /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/fields/26071N_INSP_iso_tsvf_bela/density.nii.gz
Saving /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/fields/26071N_INSP_iso_tsvf_bela/youngs_modulus.nii.gz
Saving /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/fields/26071N_INSP_iso_tsvf_bela/poisson_ratio.nii.gz
Saving /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/fields/26071N_INSP_iso_tsvf_bela_label.nii.gz
INFO: /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/meshes/26071N_INSP_iso_tsvf_lung_pyg.xdmf missing; Running stage generate_tetrahedral_mesh
Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-08-08/26071N/masks/26071N_INSP_iso_tsvf_lung.nii.gz
Generating tetrahedral mesh
Running pygalmesh generation
WARNING: mask is not an integer dtype

In [25]:
jobs.loc[:, 'job_id'] = pd.NA

In [28]:
%autoreload
jobs = ps.submit(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params_json,params_hash,params.config,params.data_name,params.data_root,params.subject,params.mat_tag,params.fwd_tag,params.mat_type,params.variant
0,jobead9ab1e5bc03c66,SUBMITTED,1,7159234,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",ead9ab1e5bc03c66,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,16514P,bela,linear,linear,2026-08-08
1,job96ef0272ef81ee7e,SUBMITTED,1,7159235,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",96ef0272ef81ee7e,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,20748Q,bela,linear,linear,2026-08-08
2,job4d5d759871906077,SUBMITTED,1,7159236,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",4d5d759871906077,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,11007Z,bela,linear,linear,2026-08-08
3,job62c1bdeb21500ce0,SUBMITTED,1,7159237,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",62c1bdeb21500ce0,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,14771Z,bela,linear,linear,2026-08-08
4,job1a856f1cecae8f51,SUBMITTED,1,7159238,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",1a856f1cecae8f51,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,13651K,bela,linear,linear,2026-08-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job22f2adacb02a421c,SUBMITTED,1,7160229,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",22f2adacb02a421c,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,20519B,bela,linear,linear,2026-08-08
996,jobb1e67f498dc392b6,SUBMITTED,1,7160230,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",b1e67f498dc392b6,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,12294H,bela,linear,linear,2026-08-08
997,job2f617f39d23060c8,SUBMITTED,1,7160231,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",2f617f39d23060c8,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,23123R,bela,linear,linear,2026-08-08
998,jobbef061b64dfcfc4e,SUBMITTED,1,7160232,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",bef061b64dfcfc4e,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,16546C,bela,linear,linear,2026-08-08
999,job2ee27f6ba5ec4ec2,SUBMITTED,1,7160233,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,"{""config"": ""2026-08-08_config.yaml"", ""data_nam...",2ee27f6ba5ec4ec2,/projectnb/batmanlab/mragoza/lung-project/note...,COPDGene,/restricted/projectnb/batmanlab/mragoza/data/C...,11099E,bela,linear,linear,2026-08-08