In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pwd

'/projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene'

In [2]:
import sys, os

def add_path(p: str):
    if p not in sys.path:
        sys.path.append(p)

add_path(os.environ['LP_ROOT'])
import project

add_path(os.environ['PROJECT'] + '/' + 'param_search')
import param_search as ps

ps.set_backend('sge')
ps.set_verbose(False)

# Gather examples

In [3]:
from pathlib import Path
#data_root = Path(os.environ['LP_ROOT'] / 'data' / 'COPDGene'
data_root = Path(os.environ['PRIVATE']) / 'data' / 'COPDGene'
data_root.is_dir()

True

In [4]:
import pandas as pd
subject_file = data_root / 'sample1000_2025-07-22.csv'
subject_list = list(pd.read_csv(subject_file, sep='\t').sid)
len(subject_list)

1000

# Setup experiment

In [6]:
base_dir = '2026-09-15_preprocess'

template = '''\
#!/bin/bash -l
#$ -N {job_name}
#$ -P batmanlab
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_memory=32G
#$ -l h_rt=3:00:00
set -eo pipefail

mamba activate $PROJECT/mambaforge/envs/warp

export PYTHONPATH=$LP_ROOT:$PROJECT:$PYTHOPATH

python $LP_ROOT/scripts/preprocess.py {config} \\
    --set dataset.subjects=[{subject}] \\
    --set dataset.variant={variant} \\
    --set dataset.pipeline_tags.mesh_generation={mesh_tag} \\
    --set dataset.pipeline_tags.forward_simulation={sim_tag} \\
    --set preprocessing.mesh_generation.pygalmesh_kws.max_cell_circumradius={cell_radius} \\
    --set preprocessing.forward_simulation.pde_solver.material_type={material_type}

'''
name_format = 'job_{params_hash}'

grid = ps.param_grid(
    config='2026-09-15_config.yaml',
    subject=subject_list,
    variant='2026-09-15',
    sim_tag='LE',
    mesh_tag='rad',
    cell_radius=3.75,
    material_type=['LE', 'VK', 'NH', 'YH']
)

len(grid)

4000

In [7]:
radius_overrides = { # manually tested to resolve seg faults
    '17790S': 4.00,
    '19410S': 4.75,
    '13533E': 4.25,
    '17266B': 4.75,
}

for p in grid:
    sid = p['subject']

    p['sim_tag'] = p['material_type']
    
    if sid in radius_overrides:
        p['cell_radius'] = radius_overrides[sid]

In [8]:
jobs = ps.setup(base_dir, template, name_format, grid, overwrite=False)
jobs

OSError: /projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene/2026-09-15_preprocess/job_e65366df471e0e9b/run.sh already exists

In [29]:
jobs = ps.submit(jobs)

In [9]:
jobs = ps.load(base_dir)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.cell_radius,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
0,job_e65366df471e0e9b,SUBMITTED,1,7696868,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,LE,NaN,None,None,None,None,False,None,None
1,job_3c3c297a25df66fc,SUBMITTED,1,7696869,None,None,Module make_bsr_mm_count_coeffs__locals__bsr_m...,"Warp UserWarning: grad() call for function ""st...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,VK,NaN,None,None,None,None,False,None,None
2,job_46137611115dcb44,SUBMITTED,1,7696870,None,None,Module warp.sparse ea33bb7 load on device 'cud...,"File ""/projectnb/batmanlab/mragoza/lung-proj...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,NH,NaN,None,None,None,None,False,None,None
3,job_dc5f8615d728c241,SUBMITTED,1,7696871,None,None,Warp 1.15.0 initialized:\n CUDA Toolkit 12.9...,"File ""/projectnb/batmanlab/mragoza/mambaforg...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,YH,NaN,None,None,None,None,False,None,None
4,job_fefa38d6edfcd4c7,SUBMITTED,1,7696872,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,LE,NaN,None,None,None,None,False,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,job_757864529e11552a,PENDING,1,7700925,None,None,None,None,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,YH,NaN,2026-09-22T22:25:43,status,None,None,False,None,None
3996,job_a436b6816739afb6,PENDING,1,7700926,None,None,None,None,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,LE,NaN,2026-09-22T22:25:43,status,None,None,False,None,None
3997,job_ccd3dda49b63c90e,PENDING,1,7700927,None,None,None,None,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,VK,NaN,2026-09-22T22:25:43,status,None,None,False,None,None
3998,job_e8d1a5349e328414,PENDING,1,7700928,None,None,None,None,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,NH,NaN,2026-09-22T22:25:43,status,None,None,False,None,None
3999,job_857cca73d836b6d8,PENDING,1,7700929,None,None,None,None,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,YH,NaN,2026-09-22T22:25:43,status,None,None,False,None,None

In [10]:
%autoreload
jobs = ps.recover(jobs)
jobs = ps.status(jobs)
jobs = ps.history(jobs) # not working for SGE backend; job_state may be stale
jobs = ps.collect(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.cell_radius,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
0,job_e65366df471e0e9b,SUBMITTED,1,7696868,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,LE,NaN,None,None,None,None,False,<NA>,<NA>
1,job_3c3c297a25df66fc,SUBMITTED,1,7696869,None,None,Module make_bsr_mm_count_coeffs__locals__bsr_m...,"Warp UserWarning: grad() call for function ""st...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,VK,NaN,None,None,None,None,False,<NA>,<NA>
2,job_46137611115dcb44,SUBMITTED,1,7696870,None,None,Module warp.sparse ea33bb7 load on device 'cud...,"File ""/projectnb/batmanlab/mragoza/lung-proj...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,NH,NaN,None,None,None,None,False,<NA>,<NA>
3,job_dc5f8615d728c241,SUBMITTED,1,7696871,None,None,Warp 1.15.0 initialized:\n CUDA Toolkit 12.9...,"File ""/projectnb/batmanlab/mragoza/mambaforg...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,YH,NaN,None,None,None,None,False,<NA>,<NA>
4,job_fefa38d6edfcd4c7,SUBMITTED,1,7696872,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,LE,NaN,None,None,None,None,False,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,job_757864529e11552a,PENDING,1,7700925,None,None,Warp 1.15.0 initialized:\n CUDA Toolkit 12.9...,"File ""/projectnb/batmanlab/mragoza/mambaforg...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,YH,NaN,2026-09-22T22:25:43,status,None,None,False,<NA>,<NA>
3996,job_a436b6816739afb6,PENDING,1,7700926,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,LE,NaN,2026-09-22T22:25:43,status,None,None,False,<NA>,<NA>
3997,job_ccd3dda49b63c90e,PENDING,1,7700927,None,None,Module make_bsr_mm_count_coeffs__locals__bsr_m...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,VK,NaN,2026-09-22T22:25:43,status,None,None,False,<NA>,<NA>
3998,job_e8d1a5349e328414,PENDING,1,7700928,None,None,Module warp.sparse ea33bb7 load on device 'cud...,"File ""/projectnb/batmanlab/mragoza/lung-proj...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,NH,NaN,2026-09-22T22:25:43,status,None,None,False,<NA>,<NA>
3999,job_857cca73d836b6d8,PENDING,1,7700929,None,None,Warp 1.15.0 initialized:\n CUDA Toolkit 12.9...,"File ""/projectnb/batmanlab/mragoza/mambaforg...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,3.75,YH,NaN,2026-09-22T22:25:43,status,None,None,False,<NA>,<NA>

In [11]:
jobs.groupby('job_state').count()

,job_name,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,script_path,...,params.cell_radius,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime
job_state,,,,,,,,,,,,,,,,,,,,,
PENDING,3969,3969,3969,0,0,3969,3969,3969,3969,3969,...,3969,3969,0,3969,3969,0,0,3969,0,0
RUNNING,7,7,7,7,7,7,7,7,7,7,...,7,7,0,7,7,0,0,7,0,0
SUBMITTED,24,24,24,0,0,24,24,24,24,24,...,24,24,0,0,0,0,0,24,0,0

In [12]:
def classify_error(stderr: str):

    if pd.isnull(stderr):
        return 'No stderr file'
        
    elif not str(stderr).strip():
        return 'No error message'

    elif 'Segmentation fault' in stderr:
        return 'Segmentation fault'
    
    elif 'CUDA out of memory' in stderr or ('Failed to allocate' in stderr and "bytes on device 'cuda" in stderr):
        return 'CUDA out of memory'

    elif 'Warp CUDA error' in stderr:
        return 'Warp CUDA error'
        
    elif 'Non-positive density' in stderr:
        return 'Non-positive density'
        
    elif 'construct initial points' in stderr or 'Exuding' in stderr or ('Moving #' in stderr and 'addr:' in stderr):
        return 'pygalmesh output'

    elif 'WARNING' in stderr:
        return 'Uncategorized warning'

    elif 'Warp UserWarning' in stderr:
        return 'Warp user warning'

    elif 'Line search failed' in stderr:
        return 'Line search failed'

    return 'Uncategorized error'

jobs['error_type'] = jobs.stderr.map(classify_error)
jobs.groupby('error_type')[['job_name']].count()

                     job_name
error_type
Line search failed        370
No error message         2621
Uncategorized error       998
Warp user warning          11

In [21]:
selection = jobs.error_type.isin(['Line search failed']) & (jobs['params.material_type'] == 'VK')
error_jobs = jobs[selection]
error_jobs.groupby(['params.material_type']).count()

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.cell_radius,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
params.material_type,,,,,,,,,,,,,,,,,,,,,
VK,4,4,4,4,0,0,4,4,4,4,...,4,0,4,4,0,0,4,0,0,4

In [28]:
job = error_jobs.iloc[1]
print(job)
print(job.stdout)
print(job.stderr)

job_name                                             job_487fe94a4d5c7e85
job_state                                                         PENDING
n_submits                                                               1
job_id                                                            7697791
node_id                                                              None
runtime                                                              None
stdout                  Module warp.sparse ea33bb7 load on device 'cud...
stderr                    File "/projectnb/batmanlab/mragoza/lung-proj...
base_dir                /projectnb/batmanlab/mragoza/lung-project/note...
work_dir                /projectnb/batmanlab/mragoza/lung-project/note...
script_path             /projectnb/batmanlab/mragoza/lung-project/note...
output_path             /projectnb/batmanlab/mragoza/lung-project/note...
log_dir                 /projectnb/batmanlab/mragoza/lung-project/note...
stdout_path             /projectnb/batmanlab/mragoza/lung-project/note...
stderr_path             /projectnb/batmanlab/mragoza/lung-project/note...
params_json             {"cell_radius": 3.75, "config": "2026-09-15_co...
params_hash                                              487fe94a4d5c7e85
params.config           /projectnb/batmanlab/mragoza/lung-project/note...
params.subject                                                     12519F
params.variant                                                 2026-09-15
params.sim_tag                                                         VK
params.mesh_tag                                                       rad
params.cell_radius                                                   3.75
params.material_type                                                   VK
array_idx                                                             NaN
last_live_at                                          2026-09-22T22:25:43
state_source                                                       status
finalized                                                            None
finalized_at                                                         None
output_exists                                                       False
output_fsize                                                         <NA>
output_mtime                                                         <NA>
error_type                                             Line search failed
Name: 921, dtype: object
Module warp.sparse ea33bb7 load on device 'cuda:0' took 1.93 ms  (cached)
Module _bsr_assign_copy_blocks_88f1eeb0 da01f6f load on device 'cuda:0' took 1.82 ms  (cached)
Module make_bsr_mm_count_coeffs__locals__bsr_mm_count_coeffs_f2c69ab8 f2c69ab load on device 'cuda:0' took 1.54 ms  (cached)
Module _bsr_axpy_add_block_6d131d4e caeddea load on device 'cuda:0' took 1.67 ms  (cached)
Module _bsr_mm_compute_values_5abd2ed6 84ace5e load on device 'cuda:0' took 1.29 ms  (cached)
Module _bsr_get_diag_kernel_cb562821 a6c9460 load on device 'cuda:0' took 2.28 ms  (cached)
Module _extract_inverse_diagonal_blocked_859f7901 048188e load on device 'cuda:0' took 2.28 ms  (cached)
Module _create_tiled_dot_kernels__locals__block_dot_kernel_053ee49e d0147c9 load on device 'cuda:0' took 1.59 ms  (cached)
Module _create_tiled_dot_kernels__locals__block_sum_kernel_09cac745 f3ea71e load on device 'cuda:0' took 1.26 ms  (cached)
Module make_gmres_solve_least_squares_kernel_tiled__locals__gmres_solve_least_squares_tiled_dcd12f1a 62d4333 load on device 'cuda:0' took 1.78 ms  (cached)
Module warp.optim.linear 348a9a7 load on device 'cuda:0' took 3.27 ms  (cached)
Module warp.optim.linear deb085b load on device 'cuda:0' took 3.11 ms  (cached)
Module warp.optim.linear be71e6e load on device 'cuda:0' took 3.69 ms  (cached)
Module _diag_mv_kernel_2fb9736a 701a2a4 load on device 'cuda:0' took 1.29 ms  (cached)
Module warp.optim.linear 0539a03 load on device 'cuda:0' took 3.19 ms  (cached)
Module map_mul bdc32e5 load on device 'cuda:0' took 1.40 ms  (cached)
Module map_add 156e94c load on device 'cuda:0' took 1.35 ms  (cached)
Module map_sub 9c9303c load on device 'cuda:0' took 9.59 ms  (cached)
Module warp.optim.linear bb62984 load on device 'cuda:0' took 3.63 ms  (cached)

  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/pipelines/copdgene.py", line 73, in preprocess
    run_stage(
  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/runner.py", line 31, in run_stage
    return True, func(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/lung-project/project/preprocessing/stages.py", line 442, in simulate_displacement_field
    u_sim = adapter.simulate_displacement(mesh, unit_m, bc_spec) # meters
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/lung-project/project/physics/adapter.py", line 185, in simulate_displacement
    u_sim = self.pde_solver.solve_forward(mu, lam, rho, u_bc)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/lung-project/project/physics/warp/solver.py", line 192, in solve_forward
    self.solve_forward_system(mu, lam, rho, u_sim)
  File "/projectnb/batmanlab/mragoza/lung-project/project/physics/warp/solver.py", line 253, in solve_forward_system
    return self.solve_newton_method(mu, lam, rho, u)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/lung-project/project/physics/warp/solver.py", line 335, in solve_newton_method
    raise RuntimeError(f'Line search failed at Newton step {step + 1}')
RuntimeError: Line search failed at Newton step 57

In [18]:
jobs.loc[selection, 'job_id'] = pd.NA

In [19]:
jobs = ps.submit(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_b4c7852d20263f79,RUNNING,1,7682992,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
1,job_6dde2dde115cb9f0,RUNNING,1,7682993,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
2,job_149a9ed3539d6c51,RUNNING,1,7682994,scc-j03,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
3,job_07d5ae035ad74690,RUNNING,1,7682995,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
4,job_ea6b83d9cf2b90d0,RUNNING,1,7682996,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_9814db642769461b,PENDING,1,7683988,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
996,job_19763e21de3bd70a,PENDING,1,7683989,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
997,job_05071e08c3704f4b,PENDING,1,7683990,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
998,job_dc35c263f9db7119,PENDING,1,7683991,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
999,job_662514647efd74ad,PENDING,1,7683992,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning

# Registration validation

In [29]:
job

job_name                                             job_487fe94a4d5c7e85
job_state                                                         PENDING
n_submits                                                               1
job_id                                                            7697791
node_id                                                              None
runtime                                                              None
stdout                  Module warp.sparse ea33bb7 load on device 'cud...
stderr                    File "/projectnb/batmanlab/mragoza/lung-proj...
base_dir                /projectnb/batmanlab/mragoza/lung-project/note...
work_dir                /projectnb/batmanlab/mragoza/lung-project/note...
script_path             /projectnb/batmanlab/mragoza/lung-project/note...
output_path             /projectnb/batmanlab/mragoza/lung-project/note...
log_dir                 /projectnb/batmanlab/mragoza/lung-project/note...
stdout_path             /projectnb/batmanlab/mragoza/lung-project/note...
stderr_path             /projectnb/batmanlab/mragoza/lung-project/note...
params_json             {"cell_radius": 3.75, "config": "2026-09-15_co...
params_hash                                              487fe94a4d5c7e85
params.config           /projectnb/batmanlab/mragoza/lung-project/note...
params.subject                                                     12519F
params.variant                                                 2026-09-15
params.sim_tag                                                         VK
params.mesh_tag                                                       rad
params.cell_radius                                                   3.75
params.material_type                                                   VK
array_idx                                                             NaN
last_live_at                                          2026-09-22T22:25:43
state_source                                                       status
finalized                                                            None
finalized_at                                                         None
output_exists                                                       False
output_fsize                                                         <NA>
output_mtime                                                         <NA>
error_type                                             Line search failed
Name: 921, dtype: object

In [31]:
# load mesh
mesh_path = '/restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-09-15/12519F/meshes/12519F_EXP_iso_v3d_gil_INSP_lung_rad_bela_int.xdmf'
mesh = project.fileio.load_meshio(mesh_path)
mesh

Loading /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-09-15/12519F/meshes/12519F_EXP_iso_v3d_gil_INSP_lung_rad_bela_int.xdmf

<meshio mesh object>
  Number of points: 36328
  Number of cells:
    tetra: 178675
  Point data: medit:ref, image, u_reg, E, nu, rho
  Cell data: medit:ref, label, image, u_reg, E, nu, rho

In [38]:
import numpy as np

verts = mesh.points
cells = mesh.cells_dict['tetra']

disp  = mesh.point_data['u_reg']
verts_def = verts + disp

X = verts[cells]
x = verts_def[cells]

Dm = np.stack([
    X[:,1] - X[:,0],
    X[:,2] - X[:,0],
    X[:,3] - X[:,0],
], axis=-1)

dm = np.stack([
    x[:,1] - x[:,0],
    x[:,2] - x[:,0],
    x[:,3] - x[:,0],
], axis=-1)

J = np.linalg.det(dm) / np.linalg.det(Dm)

print("registration min J:", J.min())
print("negative tets:", (J <= 0).sum())
print("small J (<0.1):", (J < 0.1).sum())
print("worst tet:", J.argmin())
print("J at FEM problem tet 118654:", J[118654])

registration min J: 0.27947042135978595
negative tets: 0
small J (<0.1): 0
worst tet: 171210
J at FEM problem tet 118654: 0.3842587031958399

In [46]:
mesh.point_data['E'].max()

np.float64(5940.127298116684)