In [21]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pwd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

'/projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene'

In [22]:
import sys, os

def add_path(p: str):
    if p not in sys.path:
        sys.path.append(p)

add_path(os.environ['LP_ROOT'])
import project

add_path(os.environ['PROJECT'] + '/' + 'param_search')
import param_search as ps

ps.set_backend('sge')
ps.set_verbose(False)

# Gather examples

In [23]:
from pathlib import Path
#data_root = Path(os.environ['LP_ROOT'] / 'data' / 'COPDGene'
data_root = Path(os.environ['PRIVATE']) / 'data' / 'COPDGene'
data_root.is_dir()

True

In [24]:
import pandas as pd
subject_file = data_root / 'sample1000_2025-07-22.csv'
subject_list = list(pd.read_csv(subject_file, sep='\t').sid)
len(subject_list)

1000

# Setup experiment

In [26]:
base_dir = '2026-09-15_preprocess'

template = '''\
#!/bin/bash -l
#$ -N {job_name}
#$ -P batmanlab
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_memory=32G
#$ -l h_rt=3:00:00
set -eo pipefail

mamba activate $PROJECT/mambaforge/envs/warp

export PYTHONPATH=$LP_ROOT:$PROJECT:$PYTHOPATH

python $LP_ROOT/scripts/preprocess.py {config} \\
    --set dataset.subjects=[{subject}] \\
    --set dataset.variant={variant} \\
    --set dataset.pipeline_tags.mesh_generation={mesh_tag} \\
    --set dataset.pipeline_tags.forward_simulation={sim_tag} \\
    --set preprocessing.mesh_generation.pygalmesh_kws.max_cell_circumradius={cell_radius} \\
    --set preprocessing.forward_simulation.pde_solver.material_type={material_type}

'''
name_format = 'job_{params_hash}'

grid = ps.param_grid(
    config='2026-09-15_config.yaml',
    subject=subject_list,
    variant='2026-09-15',
    sim_tag='LE',
    mesh_tag='rad',
    cell_radius=3.75,
    material_type=['LE', 'VK', 'NH', 'YH']
)

len(grid)

4000

In [27]:
radius_overrides = { # manually tested to resolve seg faults
    '17790S': 4.00,
    '19410S': 4.75,
    '13533E': 4.25,
    '17266B': 4.75,
}

for p in grid:
    sid = p['subject']

    p['sim_tag'] = p['material_type']
    
    if sid in radius_overrides:
        p['cell_radius'] = radius_overrides[sid]

In [28]:
jobs = ps.setup(base_dir, template, name_format, grid, overwrite=False)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,stderr_path,params_json,params_hash,params.config,params.subject,params.variant,params.sim_tag,params.mesh_tag,params.cell_radius,params.material_type
0,job_e65366df471e0e9b,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",e65366df471e0e9b,/projectnb/batmanlab/mragoza/lung-project/note...,16514P,2026-09-15,LE,rad,3.75,LE
1,job_3c3c297a25df66fc,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",3c3c297a25df66fc,/projectnb/batmanlab/mragoza/lung-project/note...,16514P,2026-09-15,VK,rad,3.75,VK
2,job_46137611115dcb44,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",46137611115dcb44,/projectnb/batmanlab/mragoza/lung-project/note...,16514P,2026-09-15,NH,rad,3.75,NH
3,job_dc5f8615d728c241,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",dc5f8615d728c241,/projectnb/batmanlab/mragoza/lung-project/note...,16514P,2026-09-15,YH,rad,3.75,YH
4,job_fefa38d6edfcd4c7,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",fefa38d6edfcd4c7,/projectnb/batmanlab/mragoza/lung-project/note...,20748Q,2026-09-15,LE,rad,3.75,LE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,job_757864529e11552a,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",757864529e11552a,/projectnb/batmanlab/mragoza/lung-project/note...,16546C,2026-09-15,YH,rad,3.75,YH
3996,job_a436b6816739afb6,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",a436b6816739afb6,/projectnb/batmanlab/mragoza/lung-project/note...,11099E,2026-09-15,LE,rad,3.75,LE
3997,job_ccd3dda49b63c90e,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",ccd3dda49b63c90e,/projectnb/batmanlab/mragoza/lung-project/note...,11099E,2026-09-15,VK,rad,3.75,VK
3998,job_e8d1a5349e328414,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",e8d1a5349e328414,/projectnb/batmanlab/mragoza/lung-project/note...,11099E,2026-09-15,NH,rad,3.75,NH
3999,job_857cca73d836b6d8,NEW,0,<NA>,<NA>,<NA>,<NA>,<NA>,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,<NA>,"{""cell_radius"": 3.75, ""config"": ""2026-09-15_co...",857cca73d836b6d8,/projectnb/batmanlab/mragoza/lung-project/note...,11099E,2026-09-15,YH,rad,3.75,YH

In [ ]:
jobs = ps.submit(jobs)

In [11]:
jobs = ps.load(base_dir)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_b4c7852d20263f79,RUNNING,1,7682992,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
1,job_6dde2dde115cb9f0,RUNNING,1,7682993,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
2,job_149a9ed3539d6c51,RUNNING,1,7682994,scc-j03,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
3,job_07d5ae035ad74690,RUNNING,1,7682995,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
4,job_ea6b83d9cf2b90d0,RUNNING,1,7682996,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_9814db642769461b,PENDING,1,7683988,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
996,job_19763e21de3bd70a,PENDING,1,7683989,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
997,job_05071e08c3704f4b,PENDING,1,7683990,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
998,job_dc35c263f9db7119,PENDING,1,7683991,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning
999,job_662514647efd74ad,PENDING,1,7683992,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,None,None,Uncategorized warning

In [12]:
%autoreload
jobs = ps.recover(jobs)
jobs = ps.status(jobs)
jobs = ps.history(jobs) # not working for SGE backend; job_state may be stale
jobs = ps.collect(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_b4c7852d20263f79,RUNNING,1,7682992,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
1,job_6dde2dde115cb9f0,RUNNING,1,7682993,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
2,job_149a9ed3539d6c51,RUNNING,1,7682994,scc-j03,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
3,job_07d5ae035ad74690,RUNNING,1,7682995,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
4,job_ea6b83d9cf2b90d0,RUNNING,1,7682996,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_9814db642769461b,PENDING,1,7683988,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
996,job_19763e21de3bd70a,PENDING,1,7683989,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
997,job_05071e08c3704f4b,PENDING,1,7683990,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
998,job_dc35c263f9db7119,PENDING,1,7683991,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
999,job_662514647efd74ad,PENDING,1,7683992,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning

In [14]:
jobs.groupby('job_state').count()

,job_name,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,script_path,...,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
job_state,,,,,,,,,,,,,,,,,,,,,
PENDING,990,990,990,0,0,990,990,990,990,990,...,990,0,990,990,0,0,990,0,0,990
RUNNING,9,9,9,9,9,9,9,9,9,9,...,9,0,9,9,0,0,9,0,0,9
SUBMITTED,1,1,1,0,0,1,1,1,1,1,...,1,0,1,1,0,0,1,0,0,1

In [15]:
def classify_error(stderr: str):

    if pd.isnull(stderr):
        return 'No stderr file'
        
    elif not str(stderr).strip():
        return 'No error message'

    elif 'Segmentation fault' in stderr:
        return 'Segmentation fault'
    
    elif 'CUDA out of memory' in stderr or ('Failed to allocate' in stderr and "bytes on device 'cuda" in stderr):
        return 'CUDA out of memory'

    elif 'Warp CUDA error' in stderr:
        return 'Warp CUDA error'
        
    elif 'Non-positive density' in stderr:
        return 'Non-positive density'
        
    elif 'construct initial points' in stderr or 'Exuding' in stderr or ('Moving #' in stderr and 'addr:' in stderr):
        return 'pygalmesh output'

    elif 'WARNING' in stderr:
        return 'Uncategorized warning'

    return 'Uncategorized error'

jobs['error_type'] = jobs.stderr.map(classify_error)
jobs.groupby('error_type')[['job_name']].count()

                       job_name
error_type
No error message              4
Uncategorized warning       996

In [16]:
selection = jobs.error_type.isin(['Uncategorized warning'])
error_jobs = jobs[selection]
error_jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_b4c7852d20263f79,RUNNING,1,7682992,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
1,job_6dde2dde115cb9f0,RUNNING,1,7682993,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
2,job_149a9ed3539d6c51,RUNNING,1,7682994,scc-j03,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
3,job_07d5ae035ad74690,RUNNING,1,7682995,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
4,job_ea6b83d9cf2b90d0,RUNNING,1,7682996,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_9814db642769461b,PENDING,1,7683988,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
996,job_19763e21de3bd70a,PENDING,1,7683989,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
997,job_05071e08c3704f4b,PENDING,1,7683990,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
998,job_dc35c263f9db7119,PENDING,1,7683991,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
999,job_662514647efd74ad,PENDING,1,7683992,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning

In [18]:
job = error_jobs.iloc[-1]
print(job)
print(job.stdout)
print(job.stderr)

job_name                                             job_662514647efd74ad
job_state                                                         PENDING
n_submits                                                               1
job_id                                                            7683992
node_id                                                              None
runtime                                                              None
stdout                  Module warp._src.fem.field.virtual.dyn.dispatc...
stderr                  WARNING: Interpolation points outside domain: ...
base_dir                /projectnb/batmanlab/mragoza/lung-project/note...
work_dir                /projectnb/batmanlab/mragoza/lung-project/note...
script_path             /projectnb/batmanlab/mragoza/lung-project/note...
output_path             /projectnb/batmanlab/mragoza/lung-project/note...
log_dir                 /projectnb/batmanlab/mragoza/lung-project/note...
stdout_path             /projectnb/batmanlab/mragoza/lung-project/note...
stderr_path             /projectnb/batmanlab/mragoza/lung-project/note...
params_json             {"cell_radius": 3.75, "config": "2026-09-15_co...
params_hash                                              662514647efd74ad
params.config           /projectnb/batmanlab/mragoza/lung-project/note...
params.subject                                                     11099E
params.variant                                                 2026-09-15
params.sim_tag                                                         LE
params.mesh_tag                                                       rad
params.cell_radius                                                   3.75
params.material_type                                               linear
array_idx                                                             NaN
last_live_at                                          2026-09-21T19:54:00
state_source                                                       status
finalized                                                            None
finalized_at                                                         None
output_exists                                                       False
output_fsize                                                         <NA>
output_mtime                                                         <NA>
error_type                                          Uncategorized warning
Name: 999, dtype: object
Module warp._src.fem.field.virtual.dyn.dispatch_bilinear_kernel_fn_75488a1a b6bbaad load on device 'cuda:0' took 51.86 ms  (cached)
Module make_bsr_mv_tiled_kernel__locals__bsr_mv_tiled_kernel_c7dc0858 931cb0f load on device 'cuda:0' took 101.03 ms  (cached)
Module warp.fem.linalg dcc28ab load on device 'cuda:0' took 2.67 ms  (cached)
Module warp.sparse ea33bb7 load on device 'cuda:0' took 2.82 ms  (cached)
Module _bsr_assign_copy_blocks_88f1eeb0 da01f6f load on device 'cuda:0' took 1.98 ms  (cached)
Module make_bsr_mm_count_coeffs__locals__bsr_mm_count_coeffs_f2c69ab8 f2c69ab load on device 'cuda:0' took 1.90 ms  (cached)
Module _bsr_axpy_add_block_6d131d4e caeddea load on device 'cuda:0' took 2.54 ms  (cached)
Module _bsr_mm_compute_values_5abd2ed6 84ace5e load on device 'cuda:0' took 2.43 ms  (cached)
Module _bsr_get_diag_kernel_cb562821 a6c9460 load on device 'cuda:0' took 3.67 ms  (cached)
Module _extract_inverse_diagonal_blocked_859f7901 048188e load on device 'cuda:0' took 2.53 ms  (cached)
Module _create_tiled_dot_kernels__locals__block_dot_kernel_053ee49e d0147c9 load on device 'cuda:0' took 2.11 ms  (cached)
Module _create_tiled_dot_kernels__locals__block_sum_kernel_09cac745 f3ea71e load on device 'cuda:0' took 2.33 ms  (cached)
Module warp.optim.linear 4b52d9b load on device 'cuda:0' took 3.57 ms  (cached)
Module _diag_mv_kernel_2fb9736a 701a2a4 load on device 'cuda:0' took 1.90 ms  (cached)
Module warp.optim.linear 28ee43b load on device 'cuda:0' took 3.49 ms  (cached)
Module warp.optim.linear f83bd16 load on device 'cuda:0' took 3.94 ms  (cached)
Module map_add 156e94c load on device 'cuda:0' took 2.48 ms  (cached)
Saving /restricted/projectnb/batmanlab/mragoza/data/COPDGene/Processed/2026-09-15/11099E/meshes/11099E_EXP_iso_v3d_gil_INSP_lung_rad_bela_int_LE.xdmf
[Example 1/1] Done

WARNING: Interpolation points outside domain: 21
WARNING: Interpolation points outside domain: 21
WARNING: Interpolation points outside domain: 21
WARNING: Interpolation points outside domain: 21
WARNING: Interpolation points outside domain: 21

In [18]:
jobs.loc[selection, 'job_id'] = pd.NA

In [19]:
jobs = ps.submit(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.material_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_b4c7852d20263f79,RUNNING,1,7682992,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
1,job_6dde2dde115cb9f0,RUNNING,1,7682993,scc-j01,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
2,job_149a9ed3539d6c51,RUNNING,1,7682994,scc-j03,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
3,job_07d5ae035ad74690,RUNNING,1,7682995,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
4,job_ea6b83d9cf2b90d0,RUNNING,1,7682996,scc-504,00:01:57,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_9814db642769461b,PENDING,1,7683988,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
996,job_19763e21de3bd70a,PENDING,1,7683989,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
997,job_05071e08c3704f4b,PENDING,1,7683990,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
998,job_dc35c263f9db7119,PENDING,1,7683991,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning
999,job_662514647efd74ad,PENDING,1,7683992,None,None,Module warp._src.fem.field.virtual.dyn.dispatc...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,2026-09-21T19:54:00,status,None,None,False,<NA>,<NA>,Uncategorized warning