In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget
%pwd

'/projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene'

In [2]:
import sys, os

def add_path(p: str):
    if p not in sys.path:
        sys.path.append(p)

add_path(os.environ['LP_ROOT'])
import project

add_path(os.environ['PROJECT'] + '/' + 'param_search')
import param_search as ps

ps.set_backend('sge')
ps.set_verbose(False)

# Gather examples

In [3]:
from pathlib import Path
#data_root = Path(os.environ['LP_ROOT'] / 'data' / 'COPDGene'
data_root = Path(os.environ['PRIVATE']) / 'data' / 'COPDGene'
data_root.is_dir()

True

In [4]:
import pandas as pd
subject_file = data_root / 'sample1000_2025-07-22.csv'
subject_list = list(pd.read_csv(subject_file, sep='\t').sid)
len(subject_list)

1000

# Setup experiment

In [5]:
base_dir = '2026-09-15_preprocess'

template = '''\
#!/bin/bash -l
#$ -N {job_name}
#$ -P batmanlab
#$ -pe omp 4
#$ -l gpus=1
#$ -l gpu_memory=32G
#$ -l h_rt=3:00:00
set -eo pipefail

mamba activate $PROJECT/mambaforge/envs/warp

export PYTHONPATH=$LP_ROOT:$PROJECT:$PYTHOPATH

python $LP_ROOT/scripts/preprocess.py {config} \\
    --set dataset.subjects=[{subject}] \\
    --set dataset.variant={variant} \\
    --set dataset.pipeline_tags.forward_simulation={fwd_tag} \\
    --set preprocessing.forward_simulation.pde_solver.material_type={mat_type}

'''
name_format = 'job_{params_hash}'

grid = ps.param_grid(
    config='2026-09-15_config.yaml',
    subject=subject_list,
    variant='2026-09-15',
    fwd_tag='LE',
    mat_type='linear'
)

len(grid)

1000

In [29]:
jobs = ps.setup(base_dir, template, name_format, grid, overwrite=False)
jobs

OSError: /projectnb/batmanlab/mragoza/lung-project/notebooks/copdgene/2026-09-15_preprocess/job_dff3f5b4c40b66ce/run.sh already exists

In [43]:
jobs = ps.submit(jobs)

In [6]:
jobs = ps.load(base_dir)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.mat_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_dff3f5b4c40b66ce,SUBMITTED,1,7588038,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,No error message
1,job_31be35a7a76de560,SUBMITTED,1,7588039,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,Uncategorized warning
2,job_e0ce5aae5fcc604f,SUBMITTED,1,7588040,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,Uncategorized warning
3,job_63f85f291aaa8ce6,SUBMITTED,1,7588041,None,None,Module project.physics.warp.forms.linear_elast...,"\r 0%| | 0/1 [00:00<?, ?it/s]\r100%|...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,Uncategorized warning
4,job_98d44af8ed9a7c8e,SUBMITTED,1,7588042,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_664e21ade655d01d,SUBMITTED,1,7589035,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,Uncategorized warning
996,job_8c8f24c657c51935,SUBMITTED,1,7589036,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,No error message
997,job_0ad80fc533d333c8,SUBMITTED,1,7589037,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,Uncategorized warning
998,job_137c03d7e44152a3,SUBMITTED,1,7589038,None,None,Module project.physics.warp.forms.linear_elast...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,No error message
999,job_6d8af03ac425e6d6,SUBMITTED,1,7589039,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,None,None,No error message

In [7]:
%autoreload
jobs = ps.recover(jobs)
jobs = ps.status(jobs)
jobs = ps.history(jobs) # not working for SGE backend; job_state may be stale
jobs = ps.collect(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.mat_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_dff3f5b4c40b66ce,SUBMITTED,1,7588038,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message
1,job_31be35a7a76de560,SUBMITTED,1,7588039,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
2,job_e0ce5aae5fcc604f,SUBMITTED,1,7588040,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
3,job_63f85f291aaa8ce6,SUBMITTED,1,7588041,None,None,Module project.physics.warp.forms.linear_elast...,"\r 0%| | 0/1 [00:00<?, ?it/s]\r100%|...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
4,job_98d44af8ed9a7c8e,SUBMITTED,1,7588042,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_664e21ade655d01d,SUBMITTED,1,7589035,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
996,job_8c8f24c657c51935,SUBMITTED,1,7589036,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message
997,job_0ad80fc533d333c8,SUBMITTED,1,7589037,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
998,job_137c03d7e44152a3,SUBMITTED,1,7589038,None,None,Module project.physics.warp.forms.linear_elast...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message
999,job_6d8af03ac425e6d6,SUBMITTED,1,7589039,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message

In [8]:
jobs.groupby('job_state').count()

,job_name,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,script_path,...,params.mat_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
job_state,,,,,,,,,,,,,,,,,,,,,
SUBMITTED,1000,1000,1000,0,0,1000,1000,1000,1000,1000,...,1000,0,0,0,0,0,1000,0,0,1000

In [9]:
def classify_error(stderr: str):

    if pd.isnull(stderr):
        return 'No stderr file'
        
    elif not str(stderr).strip():
        return 'No error message'

    elif 'Segmentation fault' in stderr:
        return 'Segmentation fault'
    
    elif 'CUDA out of memory' in stderr or ('Failed to allocate' in stderr and "bytes on device 'cuda" in stderr):
        return 'CUDA out of memory'

    elif 'Warp CUDA error' in stderr:
        return 'Warp CUDA error'
        
    elif 'Non-positive density' in stderr:
        return 'Non-positive density'
        
    elif 'construct initial points' in stderr or 'Exuding' in stderr or ('Moving #' in stderr and 'addr:' in stderr):
        return 'pygalmesh output'

    elif 'WARNING' in stderr:
        return 'Uncategorized warning'

    return 'Uncategorized error'

jobs['error_type'] = jobs.stderr.map(classify_error)
jobs.groupby('error_type')[['job_name']].count()

                       job_name
error_type
No error message            161
Uncategorized warning       839

In [10]:
selection = jobs.error_type.isin(['Segmentation fault'])
error_jobs = jobs[selection]
error_jobs

Empty DataFrame
Columns: [job_name, job_state, n_submits, job_id, node_id, runtime, stdout, stderr, base_dir, work_dir, script_path, output_path, log_dir, stdout_path, stderr_path, params_json, params_hash, params.config, params.subject, params.variant, params.fwd_tag, params.mat_type, array_idx, last_live_at, state_source, finalized, finalized_at, output_exists, output_fsize, output_mtime, error_type]
Index: []

[0 rows x 31 columns]

In [60]:
job = error_jobs.iloc[0]
print(job)
print(job.stdout)
print(job.stderr)

job_name                                        job_77101e101b901b92
job_state                                                  SUBMITTED
n_submits                                                          1
job_id                                                       7588964
node_id                                                         None
runtime                                                         None
stdout                Kernel cache:\n     /usr2/collab/mragoza/.c...
stderr               File "/projectnb/batmanlab/mragoza/mambaforg...
base_dir           /projectnb/batmanlab/mragoza/lung-project/note...
work_dir           /projectnb/batmanlab/mragoza/lung-project/note...
script_path        /projectnb/batmanlab/mragoza/lung-project/note...
output_path        /projectnb/batmanlab/mragoza/lung-project/note...
log_dir            /projectnb/batmanlab/mragoza/lung-project/note...
stdout_path        /projectnb/batmanlab/mragoza/lung-project/note...
stderr_path        /projectnb/batmanlab/mragoza/lung-project/note...
params_json        {"config": "2026-09-15_config.yaml", "fwd_tag"...
params_hash                                         77101e101b901b92
params.config      /projectnb/batmanlab/mragoza/lung-project/note...
params.subject                                                15132W
params.variant                                            2026-09-15
params.fwd_tag                                                    LE
params.mat_type                                               linear
array_idx                                                        NaN
last_live_at                                                    None
state_source                                                    None
finalized                                                       None
finalized_at                                                    None
output_exists                                                  False
output_fsize                                                    <NA>
output_mtime                                                    <NA>
error_type                                           Warp CUDA error
Name: 924, dtype: object
   Kernel cache:
     /usr2/collab/mragoza/.cache/warp/1.15.0
Module warp.fem.utils 21e5a09 load on device 'cuda:0' took 19.89 ms  (cached)
Module warp.fem.geometry.tetmesh 681bff0 load on device 'cuda:0' took 7.62 ms  (cached)
Module warp.fem.geometry.tetmesh 9b319f1 load on device 'cuda:0' took 6.00 ms  (cached)
Module warp._src.fem.geometry.geometry.dyn.compute_cell_bounds_64bca1d6 9eddd15 load on device 'cuda:0' took 3.20 ms  (cached)
Module warp._src.fem.space.restriction.dyn.fill_element_node_indices_8d180f66 3048812 load on device 'cuda:0' took 30.22 ms  (cached)
Module warp.fem.space.restriction 6ca1790 load on device 'cuda:0' took 10.90 ms  (cached)
Module warp._src.fem.space.restriction.dyn.fill_element_node_indices_2530cabc 352fe6c load on device 'cuda:0' took 12.08 ms  (cached)
Module project.physics.warp.forms.inner_product_form_f922bc72 d8b1dac load on device 'cuda:0' took 27.96 ms  (cached)
Module _bsr_accumulate_triplet_values_af769a3c 5a4572f load on device 'cuda:0' took 3.88 ms  (cached)
Module warp.fem.dirichlet f008072 load on device 'cuda:0' took 20.79 ms  (cached)
Module make_bsr_mv_kernel__locals__bsr_mv_kernel_bef26502 b276165 load on device 'cuda:0' took 34.60 ms  (cached)
Module map_add 156e94c load on device 'cuda:0' took 2.87 ms  (cached)
Module project.physics.warp.forms.linear_elastic_residual_form_dfa98793 f32fe74 load on device 'cuda:0' took 6.96 ms  (cached)
Module warp._src.fem.field.virtual.dyn.dispatch_linear_kernel_fn_2d1fc95e 3bac161 load on device 'cuda:0' took 69.77 ms  (cached)
Module warp.fem.integrate 9a3dafc load on device 'cuda:0' took 31.21 ms  (cached)
Module project.physics.warp.forms.linear_elastic_jacobian_form_fb03f647 c9b99f3 load on device 'cuda:0' took 11.91 ms  (cached)
Module warp._src.fem.field.virtual.dyn.dispatch_bilinear_kernel_fn_75488a1a b6bbaad load on device 'cuda:0' took 209.08 ms  (error)

  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/context.py", line 10203, in launch
    module_exec = kernel.module.load(device, block_dim)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/projectnb/batmanlab/mragoza/mambaforge/envs/warp/lib/python3.11/site-packages/warp/_src/context.py", line 3996, in load
    raise Exception(f"Failed to load CUDA module '{self.name}' ({module_load_diagnostics})")
Exception: Failed to load CUDA module 'warp._src.fem.field.virtual.dyn.dispatch_bilinear_kernel_fn_75488a1a' (device='cuda:0', block_dim=256, module_hash=b6bbaad)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_free_device_async, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:915)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_cuda_event_destroy, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:3366)
Warp CUDA error 700: an illegal memory access was encountered (in function wp_cuda_event_destroy, /home/conda/feedstock_root/build_artifacts/bld/rattler-build_warp-lang_1784994304/work/warp/native/warp.cu:3366)

In [73]:
jobs.loc[selection, 'job_id'] = pd.NA

In [74]:
%autoreload
jobs = ps.submit(jobs)
jobs

,job_name,job_state,n_submits,job_id,node_id,runtime,stdout,stderr,base_dir,work_dir,...,params.mat_type,array_idx,last_live_at,state_source,finalized,finalized_at,output_exists,output_fsize,output_mtime,error_type
0,job_dff3f5b4c40b66ce,SUBMITTED,1,7588038,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message
1,job_31be35a7a76de560,SUBMITTED,1,7588039,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 4 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
2,job_e0ce5aae5fcc604f,SUBMITTED,1,7588040,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
3,job_63f85f291aaa8ce6,SUBMITTED,1,7588041,None,None,Module project.physics.warp.forms.linear_elast...,"\r 0%| | 0/1 [00:00<?, ?it/s]\r100%|...",/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
4,job_98d44af8ed9a7c8e,SUBMITTED,1,7588042,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 2 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,job_664e21ade655d01d,SUBMITTED,1,7589035,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: Interpolation points outside domain: ...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
996,job_8c8f24c657c51935,SUBMITTED,1,7589036,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message
997,job_0ad80fc533d333c8,SUBMITTED,1,7589037,None,None,Module project.physics.warp.forms.linear_elast...,WARNING: mesh has 3 components\nWARNING: Inter...,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,Uncategorized warning
998,job_137c03d7e44152a3,SUBMITTED,1,7589038,None,None,Module project.physics.warp.forms.linear_elast...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message
999,job_6d8af03ac425e6d6,SUBMITTED,1,7589039,None,None,├── 'optimizer': dict(len=2)\n | ├──...,,/projectnb/batmanlab/mragoza/lung-project/note...,/projectnb/batmanlab/mragoza/lung-project/note...,...,linear,NaN,None,None,None,None,False,<NA>,<NA>,No error message