In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib widget

In [2]:
import sys, os

print(os.getpid())

def add_path(p: str):
    if p not in sys.path:
        sys.path.append(p)

add_path(os.environ['LP_ROOT'])

import project

1147913

In [3]:
from pathlib import Path
data_root = Path(os.environ['PRIVATE']) / 'data' / 'BMC-4DCT'
for path in data_root.iterdir():
    print(path)

/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/metadata
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/filetree
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/extract_batch.sh
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/convert_dicom.sh
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/extracted
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/DISK_USAGE
/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/downloads

In [4]:
nifti_root = data_root / 'converted'
nifti_path = next(nifti_root.rglob('*.nii.gz'))
nifti_name = nifti_path.name[:-7]
nifti_name

'34_02_CHEST_WITHOUT_Thorax_20231218095234_20897r'

In [5]:
import re

name_re = re.compile(
    r'^(?P<prefix>4D|Prior2_|Next_)?'
    r'(?P<subject>\d+)_'
    r'(?P<study>\d+)_'
    r'(?P<suffix>.*)$'
)

name_re.match(nifti_name).groupdict()

{'prefix': None,
 'subject': '34',
 'study': '02',
 'suffix': 'CHEST_WITHOUT_Thorax_20231218095234_20897r'}

In [6]:
import nibabel as nib

def get_image_info(image_path):
    image_path = Path(image_path)

    assert image_path.name.endswith('.nii.gz')
    image_name = image_path.name[:-7]

    json_path = image_path.parent / f'{image_name}.json'

    ret = {
        'image_name':  str(image_name),
        'image_path':  str(image_path),
        'json_path':   str(json_path),
        'parse_error': None,
        'image_error': None,
        'json_error':  None,
    }

    parsed = name_re.match(image_name)

    if parsed:
        ret['source_prefix']  = parsed.group('prefix')
        ret['source_subject'] = parsed.group('subject')
        ret['source_study']   = parsed.group('study')
        ret['source_suffix']  = parsed.group('suffix')

    else:
        ret['parse_error'] = 'Failed to parse'

    try:
        nifti = project.fileio.load_nibabel(image_path)

        ret['image_shape']   = tuple(nifti.shape)
        ret['image_spacing'] = tuple(float(v) for v in nifti.header.get_zooms())
        ret['image_axcodes'] = nib.orientations.aff2axcodes(nifti.affine)
        ret['image_affine']  = nifti.affine.tolist()

    except FileNotFoundError:
        ret['image_error'] = 'File not found'        
    
    try:
        json_info = project.fileio.load_json(json_path)

        def _assign(dst, src, cast=None):
            value = json_info.get(src)
            if value is None:
                return
            if isinstance(value, str):
                value = value.strip()
                if not value:
                    return
            ret[dst] = cast(value) if cast else value

        _assign('modality', 'Modality')
        _assign('manufacturer', 'Manufacturer')
        _assign('device_model', 'ManufacturersModelName')
        _assign('institution_name', 'InstitutionName')
        _assign('institution_dept', 'InstitutionalDepartmentName')
        _assign('device_serial', 'DeviceSerialNumber')
        _assign('station_name', 'StationName')
        _assign('body_part', 'BodyPartExamined')
        _assign('patient_position', 'PatientPosition')
        _assign('software_version', 'SoftwareVersions')
        _assign('series_description', 'SeriesDescription')
        _assign('protocol_name', 'ProtocolName')
        _assign('scan_options', 'ScanOptions')
        _assign('image_type', 'ImageType')
        _assign('is_raw_image', 'RawImage', bool)
        _assign('series_number', 'SeriesNumber', int)
        _assign('acquisition_time', 'AcquisitionTime')
        _assign('acquisition_number', 'AcquisitionNumber', int)
        _assign('image_comments', 'ImageComments')
        _assign('convolution_kernel', 'ConvolutionKernel')
        _assign('exposure_time', 'ExposureTime')

    except FileNotFoundError:
        ret['json_error'] = 'File not found'
    
    return ret

get_image_info(nifti_path)

Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/34/34_02_CHEST_WITHOUT_Thorax_20231218095234_20897r.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/34/34_02_CHEST_WITHOUT_Thorax_20231218095234_20897r.json

{'image_name': '34_02_CHEST_WITHOUT_Thorax_20231218095234_20897r',
 'image_path': '/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/34/34_02_CHEST_WITHOUT_Thorax_20231218095234_20897r.nii.gz',
 'json_path': '/restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/34/34_02_CHEST_WITHOUT_Thorax_20231218095234_20897r.json',
 'parse_error': None,
 'image_error': None,
 'json_error': None,
 'source_prefix': None,
 'source_subject': '34',
 'source_study': '02',
 'source_suffix': 'CHEST_WITHOUT_Thorax_20231218095234_20897r',
 'image_shape': (512, 959, 7),
 'image_spacing': (0.68359375, 0.68359375, 16.5),
 'image_axcodes': ('L', 'A', 'S'),
 'image_affine': [[-0.68359375, 0.0, -0.0, 155.0500030517578],
  [-0.0, 0.68359375, -0.0, -600.7828369140625],
  [0.0, 0.0, 16.5, 1084.489990234375],
  [0.0, 0.0, 0.0, 1.0]],
 'modality': 'CT',
 'manufacturer': 'Philips',
 'device_model': 'IQon - Spectral CT',
 'device_serial': '860085',
 'station_name': 'MP1PHCT1',
 'body_part': 'CHEST',
 'patient_position': 'FFS',
 'software_version': '4.7.5',
 'series_description': 'SBI(C_SC_PE_N_B_U)_B_1.5|SPECTRAL BASED',
 'protocol_name': 'CHEST WITHOUT* /Thorax',
 'scan_options': 'HELIX',
 'image_type': ['DERIVED', 'SECONDARY', 'SBI', 'SBI', 'CSPN'],
 'is_raw_image': False,
 'series_number': 20897,
 'acquisition_time': '09:54:12.000000',
 'acquisition_number': 2,
 'convolution_kernel': 'B',
 'exposure_time': 0.221}

In [ ]:
%%time
import pandas as pd

def get_inventory(data_root):
    nifti_dir = Path(data_root) / 'converted'
    
    all_info = []
    for batch_dir in sorted(nifti_dir.iterdir()):
        
        if not batch_dir.is_dir():
            continue
            
        for image_path in sorted(batch_dir.rglob('*.nii.gz')):
            relative_path = image_path.relative_to(batch_dir)
            
            image_info = get_image_info(image_path)
            
            image_info.update({
                'batch_name': str(batch_dir.name),
                'group_name': str(relative_path.parts[0]),
                'source_dir': str(relative_path.parent),
                'image_path': image_path.relative_to(data_root).as_posix()
            })

            json_path = image_info.get('json_path')

            if json_path:
                image_info['json_path'] = Path(json_path).relative_to(data_root).as_posix()
                
            all_info.append(image_info)

    return pd.DataFrame(all_info)

inventory = get_inventory(data_root)

  0%|          | 0/2 [00:00<?, ?it/s]

Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_304.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_304.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_308.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_308.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_309.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_309.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_310.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_310.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_399.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D0010_1/4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_399.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_304.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_304.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_308.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_308.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_309.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_309.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_310.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_310.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_399.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_399.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_401.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_401.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_402.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_402.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_403.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_403.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_404.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_404.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_405.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_405.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_406.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_406.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_407.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_407.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_408.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_408.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_409.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_409.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_410.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_410.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_499.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_1/4D002_1_4D_Chest_W_O-W_CONTRAST_Onco_Body_20241219143545_499.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_304.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_304.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_308.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_308.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_309.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_309.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_310.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_310.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_399.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_2/4D002_2_SBRT_4D_CT_Onco_Body_20240604131719_399.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_3/4D002_3_4D_CHEST_OncoBody_20200513110809_1.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D002_3/4D002_3_4D_CHEST_OncoBody_20200513110809_1.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_304.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_304.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_308.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_308.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_309.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_309.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_310.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_310.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_399.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_1/4D004_1_4D_CT_Chest_Onco_Body_20250110104147_399.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D004_2/4D004_2_SBRT_BODY_Onco_CK_SBRT_SRS_20250527120842_201.nii.gz

pixdim[1,2,3] should be non-zero; setting 0 dims to 1

Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_004_01/Next_004_01_tracker_20250709230717_3.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_1.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_1.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_308.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_308.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_601.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_601.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_602.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_602.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_603.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_603.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_604.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_604.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_999.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_01/Next_005_01_5.2_GSI_CTPA_SMART_PREP_20250209204253_999.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_100_i00001.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_100_i00001.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_100_i00001a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_100_i00001a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_200.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_200.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_300.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_300.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_400.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_400.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_401.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_401.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_402.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_402.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_403.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_403.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_404.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_404.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_405.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_405.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_406.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_406.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_407.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_407.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897b.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897b.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897c.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897c.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897d.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897d.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897e.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897e.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897f.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897f.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897g.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897g.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897h.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897h.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897i.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897i.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897j.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897j.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897k.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897k.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897l.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897l.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897m.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897m.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897n.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897n.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897o.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897o.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897p.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897p.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897q.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897q.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897r.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897r.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897s.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897s.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897t.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897t.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897u.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897u.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897v.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897v.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897w.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897w.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897x.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897x.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897y.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_CTPA_Thorax_20250218163031_40897y.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_Tracker_Graph_20250218163031_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_Tracker_Graph_20250218163031_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_Tracker_Graph_20250218163031_301a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_02/Next_005_02_Tracker_Graph_20250218163031_301a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_1.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_1.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_309.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-03-25_batch/Next1/Next_005_03/Next_005_03_5.1_GSI_CT_CHEST_WITH_20250326151844_309.json

pixdim[1,2,3] should be non-zero; setting 0 dims to 1

Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/13/13_07_tracker_20251114181901_3.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_301.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_301.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_302.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_302.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_303.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_303.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_304.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_304.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_305.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_305.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_306.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_306.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_307.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_307.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_308.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_308.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_309.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_309.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_310.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_310.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_399.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_01_4D_CT_Chest_Onco_Body_20250409082040_399.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_100_i00001.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_100_i00001.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_100_i00001a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_100_i00001a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_202.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_202.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_203.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_203.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_204.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_204.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_205.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_205.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697b.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697b.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697c.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697c.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697d.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697d.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697e.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697e.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697f.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697f.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697g.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697g.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697h.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697h.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697i.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697i.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697j.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697j.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697k.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697k.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697l.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697l.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697m.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697m.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697n.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697n.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697o.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697o.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697p.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697p.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697q.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697q.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697r.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697r.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697s.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697s.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697t.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697t.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697u.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697u.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697v.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697v.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697w.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697w.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697x.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697x.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697y.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_02_LOW_DOSE_SCREEN_30BMI_Thorax_20240316090809_20697y.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_100_i00001.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_100_i00001.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_100_i00001a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_100_i00001a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_201.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_201.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_202.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_202.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_203.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_203.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_204.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_204.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_205.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_205.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_206.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_206.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_207.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_207.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_208.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_208.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897a.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897a.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897b.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897b.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897c.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897c.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897d.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897d.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897e.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897e.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897f.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897f.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897g.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897g.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897h.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897h.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897i.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897i.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897j.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897j.json
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897k.nii.gz
Loading /restricted/projectnb/batmanlab/mragoza/data/BMC-4DCT/converted/2026-07-16_batch/14/14_03_CHEST_WITHOUT_Thorax_20250116095050_20897k.json

In [14]:
error_cols = ['parse_error', 'image_error', 'json_error']

has_error = inventory[error_cols].notna()

display(has_error.sum())

inventory.loc[has_error.any(axis=1), ['image_name', *error_cols]]

parse_error     0
image_error     0
json_error     18
dtype: int64

,image_name,parse_error,image_error,json_error
1087,Next_009_03_CTA_PE_BolusTrack_20250519192005_1...,None,None,File not found
1090,Next_009_03_CTA_PE_BolusTrack_20250519192005_3...,None,None,File not found
1094,Next_009_03_CTA_PE_BolusTrack_20250519192005_5...,None,None,File not found
1096,Next_009_03_CTA_PE_BolusTrack_20250519192005_6...,None,None,File not found
1098,Next_009_03_CTA_PE_BolusTrack_20250519192005_7...,None,None,File not found
1105,Next_009_03_CTA_PE_BolusTrack_20250519192005_9...,None,None,File not found
1158,Next_009_05_I-_CHEST_Thorax_20250527174552_301...,None,None,File not found
1160,Next_009_05_I-_CHEST_Thorax_20250527174552_301...,None,None,File not found
1194,Next_009_07_5.3_GSI_CTPA_W_ABD_PELVIS_SMART_PR...,None,None,File not found
1829,Prior2_009_01_5.3_GSI_CTPA_W_ABD_PELVIS_SMART_...,None,None,File not found
1831,Prior2_009_01_5.3_GSI_CTPA_W_ABD_PELVIS_SMART_...,None,None,File not found
1833,Prior2_009_01_5.3_GSI_CTPA_W_ABD_PELVIS_SMART_...,None,None,File not found
1835,Prior2_009_01_5.3_GSI_CTPA_W_ABD_PELVIS_SMART_...,None,None,File not found
1993,12_05_5.3_GSI_CTPA_W_ABD_PELVIS_SMART_PREP_202...,None,None,File not found
3973,26_03_5.1_GSI_CT_CHEST_WITH_20230326030112_311...,None,None,File not found
3975,26_03_5.1_GSI_CT_CHEST_WITH_20230326030112_312...,None,None,File not found
4407,31_03_5.2_GSI_-_ROUTINE_CHEST_WITH_CONTRAST_20...,None,None,File not found
4409,31_03_5.2_GSI_-_ROUTINE_CHEST_WITH_CONTRAST_20...,None,None,File not found

In [95]:
def infer_role(prefix):
    if prefix == '4D':
        return '4DCT'
    elif prefix == 'Prior2_':
        return 'prior'
    elif prefix == 'Next_':
        return 'next'
    elif prefix is None:
        return 'unknown'
    raise ValueError(prefix)

inventory['subject_num'] = inventory['source_subject'].astype('Int64')
inventory['study_num']   = inventory['source_study'].astype('Int64')
inventory['scan_role']   = inventory['source_prefix'].map(infer_role)

inventory['case_id'] = (
    inventory['scan_role'].fillna('na') + '_' + 
    inventory['subject_id'].astype(str) + '_' + 
    inventory['study_id'].astype(str)
)

display(
    inventory.groupby(['case_id'], dropna=False)
    .agg(
        subject_labels=('source_subject', lambda s: tuple(sorted(set(s)))),
        study_labels=('source_study', lambda s: tuple(sorted(set(s)))),
        prefix_labels=('source_prefix', lambda s: tuple(sorted(set(s))))
    )
)

             subject_labels study_labels prefix_labels
case_id
4DCT_10_1           (0010,)         (1,)         (4D,)
4DCT_1_1             (001,)         (1,)         (4D,)
4DCT_2_1             (002,)         (1,)         (4D,)
4DCT_2_2             (002,)         (2,)         (4D,)
4DCT_2_3             (002,)         (3,)         (4D,)
...                     ...          ...           ...
unknown_53_2          (53,)        (02,)       (None,)
unknown_53_3          (53,)        (03,)       (None,)
unknown_53_4          (53,)        (04,)       (None,)
unknown_53_5          (53,)        (05,)       (None,)
unknown_53_6          (53,)        (06,)       (None,)

[276 rows x 3 columns]

In [97]:
pd.set_option('display.max_rows', 100)

id_cols = ['subject_id', 'study_id', 'scan_role']

display(
    inventory.groupby(id_cols, dropna=False)
    .size()
    .rename('n_images')
    .reset_index()
)

     subject_id  study_id scan_role  n_images
0             1         1      4DCT        12
1             1         1      next        65
2             1         1     prior         9
3             1         2      next        63
4             1         2     prior         9
..          ...       ...       ...       ...
271          53         2   unknown         8
272          53         3   unknown         8
273          53         4   unknown        12
274          53         5   unknown        27
275          53         6   unknown         8

[276 rows x 4 columns]

In [98]:
# count images by series description

display(
    inventory.groupby(['series_description'], dropna=False)
    .size()
    .rename('n_images')
    .reset_index()
    .sort_values('n_images', ascending=False)
)

                            series_description  n_images
373    SBI(C_SC_PE_N_B_U)_B_0.9_C|SAG Cal Supr       624
380    SBI(C_SC_PE_N_B_U)_B_1.5|SPECTRAL BASED       572
375  SBI(C_SC_PE_N_B_U)_B_1.5_C|IODINE DENSITY       501
378  SBI(C_SC_PE_N_B_U)_B_1.5_C|SPECTRAL BASED       225
376        SBI(C_SC_PE_N_B_U)_B_1.5_C|MONOE 40       225
..                                         ...       ...
163                               ABD PELVIS 5         1
307            Extended FOV, Pelvis, iDose (4)         1
162                            ABD PELVIS 1.25         1
159                              90% E1 Linear         1
0                                  .625MM STND         1

[434 rows x 2 columns]

In [99]:
# extract respiratory phase from 4D-CT images

phase_pattern = (
    r'^(?:Extended FOV,\s*)?'
    r'(?:\d+\s+)?'
    r'(\d+)\s*%'
)

inventory['resp_phase'] = (
    inventory['series_description']
    .astype('string')
    .str.extract(phase_pattern, expand=False)
    .astype('Int64')
)

inventory['has_phase'] = inventory['resp_phase'].notna()

phase_images = inventory.loc[inventory.has_phase]
phase_images

,image_name,image_path,json_path,parse_error,image_error,json_error,source_prefix,source_subject,source_study,source_suffix,...,is_raw_image,body_part,subject_id,study_id,scan_role,resp_phase,has_phase,subject_num,study_num,case_id
1,4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_301,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,None,None,None,4D,0010,1,4D_CT_Chest_Onco_Body_20250313135722_301,...,NaN,NaN,10,1,4DCT,0,True,10,1,4DCT_10_1
2,4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_302,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,None,None,None,4D,0010,1,4D_CT_Chest_Onco_Body_20250313135722_302,...,NaN,NaN,10,1,4DCT,10,True,10,1,4DCT_10_1
3,4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_303,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,None,None,None,4D,0010,1,4D_CT_Chest_Onco_Body_20250313135722_303,...,NaN,NaN,10,1,4DCT,20,True,10,1,4DCT_10_1
4,4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_304,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,None,None,None,4D,0010,1,4D_CT_Chest_Onco_Body_20250313135722_304,...,NaN,NaN,10,1,4DCT,30,True,10,1,4DCT_10_1
5,4D0010_1_4D_CT_Chest_Onco_Body_20250313135722_305,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,None,None,None,4D,0010,1,4D_CT_Chest_Onco_Body_20250313135722_305,...,NaN,NaN,10,1,4DCT,40,True,10,1,4DCT_10_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6178,53_01_SBRT_4D_CT_Onco_Body_20240618110033_306,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,None,None,None,None,53,01,SBRT_4D_CT_Onco_Body_20240618110033_306,...,False,CHEST,53,1,unknown,50,True,53,1,unknown_53_1
6179,53_01_SBRT_4D_CT_Onco_Body_20240618110033_307,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,None,None,None,None,53,01,SBRT_4D_CT_Onco_Body_20240618110033_307,...,False,CHEST,53,1,unknown,60,True,53,1,unknown_53_1
6180,53_01_SBRT_4D_CT_Onco_Body_20240618110033_308,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,None,None,None,None,53,01,SBRT_4D_CT_Onco_Body_20240618110033_308,...,False,CHEST,53,1,unknown,70,True,53,1,unknown_53_1
6181,53_01_SBRT_4D_CT_Onco_Body_20240618110033_309,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,None,None,None,None,53,01,SBRT_4D_CT_Onco_Body_20240618110033_309,...,False,CHEST,53,1,unknown,80,True,53,1,unknown_53_1
6182,53_01_SBRT_4D_CT_Onco_Body_20240618110033_310,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,None,None,None,None,53,01,SBRT_4D_CT_Onco_Body_20240618110033_310,...,False,CHEST,53,1,unknown,90,True,53,1,unknown_53_1

In [100]:
id_cols = ['subject_id', 'study_id', 'scan_role']

display(
    inventory.groupby(id_cols + ['has_phase'], dropna=False)
    .size()
    .rename('n_images')
    .reset_index()
)

     subject_id  study_id scan_role  has_phase  n_images
0             1         1      4DCT      False         2
1             1         1      4DCT       True        10
2             1         1      next      False        65
3             1         1     prior      False         9
4             1         2      next      False        63
..          ...       ...       ...        ...       ...
321          53         2   unknown      False         8
322          53         3   unknown      False         8
323          53         4   unknown      False        12
324          53         5   unknown      False        27
325          53         6   unknown      False         8

[326 rows x 5 columns]

In [101]:
# count images by respiratory phase
display(
    phase_images.groupby(['resp_phase'], dropna=False)
    .size()
    .rename('n_images')
    .reset_index()
)

   resp_phase  n_images
0           0        51
1          10        50
2          20        50
3          30        49
4          40        49
5          50        48
6          60        48
7          70        48
8          80        48
9          90        48

In [102]:
summary = (
    phase_images.groupby(id_cols, dropna=False)
    .agg(
        n_images=('resp_phase', 'size'),
        n_phases=('resp_phase', 'nunique'),
        phases=('resp_phase', lambda s: tuple(sorted(s)))
        
    ).reset_index()
)
summary

,subject_id,study_id,scan_role,n_images,n_phases,phases
0,1,1,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
1,2,1,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
2,2,2,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
3,4,1,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
4,6,1,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
5,7,3,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
6,8,1,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
7,8,2,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
8,9,1,4DCT,11,10,"(0, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
9,10,1,4DCT,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
10,12,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
11,13,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
12,14,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
13,15,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
14,16,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
15,17,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
16,17,3,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
17,18,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
18,19,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
19,19,2,unknown,5,5,"(0, 10, 20, 30, 40)"
20,20,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
21,22,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
22,23,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
23,26,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
24,27,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
25,28,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
26,29,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
27,30,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
28,31,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
29,32,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
30,33,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
31,34,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
32,36,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
33,37,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
34,38,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
35,39,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
36,40,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
37,40,5,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
38,42,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
39,42,4,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
40,43,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
41,44,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
42,45,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
43,47,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
44,48,1,unknown,3,3,"(0, 10, 20)"
45,49,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
46,50,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
47,51,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
48,52,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
49,53,1,unknown,10,10,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"

In [103]:
expected_phases = tuple(range(0, 100, 10))

summary[summary.phases != expected_phases]

,subject_id,study_id,scan_role,n_images,n_phases,phases
8,9,1,4DCT,11,10,"(0, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90)"
19,19,2,unknown,5,5,"(0, 10, 20, 30, 40)"
44,48,1,unknown,3,3,"(0, 10, 20)"

In [71]:
# inspect duplicate phases

display(
    phase_images.loc[
        phase_images.duplicated(id_cols + ['resp_phase'], keep=False),
        id_cols + ['image_name', 'series_description', 'image_shape']
    ]
)

,subject_id,study_id,scan_role,image_name,series_description,image_shape
132,9,1,4DCT,4D009_1_4D_CT_Chest_Onco_Body_20250225134258_310,"Extended FOV, 10 0% E1 Linear","(512, 512, 161)"
133,9,1,4DCT,4D009_1_4D_CT_Chest_Onco_Body_20250225134258_311,"Extended FOV, 0 0% E1 Linear","(512, 512, 161)"

In [72]:
inventory.to_csv(data_root / 'metadata' / 'inventory.csv', index=False)

In [130]:
# select phase images that loaded successfully

phase_manifest = inventory.loc[
    inventory.resp_phase.notna() &
    inventory.image_error.isna() &
    inventory.json_error.isna()
].copy()

# record whether cases have the expected phase set

case_phases = phase_manifest.groupby('case_id')['resp_phase'].agg(
    lambda s: tuple(sorted(s))
)

phase_manifest['case_phases'] = phase_manifest['case_id'].map(case_phases)
phase_manifest['case_valid'] = phase_manifest['case_phases'].map(expected_phases.__eq__)

columns = [
    'case_id', 'subject_id', 'study_id', 'scan_role', 'resp_phase',
    'image_path', 'series_description', 'case_phases', 'case_valid'
]

phase_manifest = (
    phase_manifest[columns]
    .sort_values(['case_id', 'resp_phase'])
    .reset_index(drop=True)
)
phase_manifest

,case_id,subject_id,study_id,scan_role,resp_phase,image_path,series_description,case_phases,case_valid
0,4DCT_10_1,10,1,4DCT,0,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,0 0% Linear,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
1,4DCT_10_1,10,1,4DCT,10,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,10 10% Linear,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
2,4DCT_10_1,10,1,4DCT,20,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,20 20% Linear,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
3,4DCT_10_1,10,1,4DCT,30,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,30 30% Linear,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
4,4DCT_10_1,10,1,4DCT,40,converted/2026-03-25_batch/4DCT/4D0010_1/4D001...,40 40% Linear,"(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
...,...,...,...,...,...,...,...,...,...
484,unknown_53_1,53,1,unknown,50,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,"Extended FOV, 50% Linear","(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
485,unknown_53_1,53,1,unknown,60,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,"Extended FOV, 60% Linear","(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
486,unknown_53_1,53,1,unknown,70,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,"Extended FOV, 70% Linear","(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
487,unknown_53_1,53,1,unknown,80,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,"Extended FOV, 80% Linear","(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True
488,unknown_53_1,53,1,unknown,90,converted/2026-07-16_batch/53/53_01_SBRT_4D_CT...,"Extended FOV, 90% Linear","(0, 10, 20, 30, 40, 50, 60, 70, 80, 90)",True

In [131]:
phase_manifest.to_csv(data_root / 'metadata' / 'phase_manifest.csv', index=False)

In [186]:
%autoreload
import project.datasets.bmc4dct

ds = project.datasets.bmc4dct.BMC4DCTDataset(data_root)
ds

In [187]:
ds.source_path(1, 1, ds.EE_RESP_STATE, asset_type='image').exists()

<string>:3: PerformanceWarning: indexing past lexsort depth may impact performance.

True

In [189]:
%autoreload
examples = ds.list_examples(subjects=[1], state_pairs=[(ds.EI_RESP_STATE, ds.EE_RESP_STATE)])
len(examples)

<string>:3: PerformanceWarning: indexing past lexsort depth may impact performance.

1

In [191]:
ex = examples[0]
project.core.utils.pprint(ex)

Example()
├── dataset:  'BMC-4DCT'
├── subject:  1
├── variant:  None
├── paths:    dict(len=3)
|   ├── 'ref_source':  PosixPath('/restricted/projectnb/batmanlab/mragoza/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_301.nii.gz')
|   ├── 'init_source': PosixPath('/restricted/projectnb/batmanlab/mragoza/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_301.nii.gz')
|   └── 'curr_source': PosixPath('/restricted/projectnb/batmanlab/mragoza/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_306.nii.gz')
└── metadata: dict(len=3)
    ├── 'study_num':  1
    ├── 'init_state': '0%'
    └── 'curr_state': '50%'

In [195]:
# source visualization
import project.core.transforms

nifti = project.core.fileio.load_nibabel(ex.paths['ref_source'])
array = nifti.get_fdata()
spacing = project.core.transforms.get_affine_spacing(nifti.affine)
array.shape, spacing

Loading /restricted/projectnb/batmanlab/mragoza/BMC-4DCT/converted/2026-03-25_batch/4DCT/4D001_1/4D001_1_4D_CT_Chest_Onco_Body_20241231083317_301.nii.gz

((512, 512, 175), array([0.9765625, 0.9765625, 2.       ]))

In [196]:
import project.visual.matplotlib as mpl_viz

mpl_viz.SliceViewer(array, spacing, cmap='Grays')

AttributeError: 'NoneType' object has no attribute 'refresh_all'